name: matchain
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.16
  # optional nearest neighbour library
  - faiss-gpu=1.7.2
  #- faiss-cpu=1.7.4
  - pip=22.3.1
  - pip:
    - networkx==2.8.8
    - tqdm==4.49.0
    - numpy==1.22.4
    - pandas==1.5.3
    - scikit-learn==1.1.2
    - scipy==1.7.1
    - gensim==4.2.0
    # thefuzz was formerly called fuzzywuzzy
    - thefuzz==0.19.0
    # optional code coverage tool
    - coverage==7.2.2
    # pytorch CUDA / GPU
    - torch==1.12.0+cu116
    - torchvision==0.13.0+cu116
    - torchaudio==0.12.0
    - --extra-index-url https://download.pytorch.org/whl/cu116
    # pytorch CPU only
    #- torch==1.12.0+cpu
    #- torchvision==0.13.0+cpu
    #- torchaudio==0.12.0
    #- --extra-index-url https://download.pytorch.org/whl/cpu
    - sentence-transformers==2.2.2
    # optional nearest neighbour library
    - nmslib==2.1.1
    # optional nearest neighbour library
    - sparse-dot-topn==0.3.4
    - -e .
